name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
          
    steps:
    - name: Check out repository
      uses: actions/checkout@main
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.x

    - name: Install project and dependencies
      run: pip install .

    - name: Install additional dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert pytest pytest-cov

    - name: Test with pytest
      run: |
        pytest --cov=process_bigraph
